### ISSUE TITLE
Clone failed

### ISSUE THREAD

**Issue by kobamkode** [connordeckers/tmux-navigator.nvim#1]
Hi, I want to report an issue regarding installation with your plugin, I got a clone failed error message like below:

```bash
fatal: could not read Username for 'https://github.com': terminal prompts disabled 
``` 

I use Lazy for my plugin manager.

**Comment by itspatchie** [comment]
Hi @kobamkode, this plugin has no interaction with Git beyond normal installation. It sounds like it's likely to be a config issue with your Git setup. 

Do you have any other plugins configured, and do they work as expected? If they do, please provide a minimal reproduction of your config displaying the problem.

**Comment by kobamkode** [comment]
Hi! thanks for super fast replay, yes you're right and I apologize to post this issue 🙏 . The installation is run smooth now. Thank you very much.
